[project]
name = "swapmeet-astana"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "efimov_as", email = "efimov_as@tochka.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.13,<4",
    "pillow>=10,<12",
    "python-dotenv>=1,<2",
]

[project.scripts]
swapmeet-astana = "bot:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
